name: kres_requests2
description: Requests app for KRES

#version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.1.7
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  path_provider: ^1.6.14
  shared_preferences: ^0.5.10
  font_awesome_flutter: ^8.8.1
  spreadsheet_decoder: ^1.2.0

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 8ea9f1ce79f04e44bd6392f4155a014b0a7eb6e8


dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/counters_import_template.png
