name: kres_requests2
description: Requests app for KRES

#version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0
  intl: ^0.17.0
  editable: ^2.0.0
  equatable: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  flutter_bloc: ^7.0.0-nullsafety.4
  get_it: ^6.0.0
  file_picker: ^3.0.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.3
  font_awesome_flutter: ^9.0.0-nullsafety
  spreadsheet_decoder: ^2.0.0
  file_selector: ^0.8.2

dev_dependencies:
  mockito: ^5.0.0
  test: ^1.16.5
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/counters_import_template.png
    - assets/sql/
