name: kres_requests2
description: Requests app for KRES

#version: 2.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  meta: ^1.3.0
  intl: ^0.17.0
  equatable: ^2.0.0
  sqflite_common_ffi: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_hooks: ^0.17.0

  flutter_modular: ^3.4.0-dev.5

  crypto: ^3.0.1
  list_ext: ^1.0.2
  rxdart: ^0.26.0
  path_provider: ^2.0.1
  shared_preferences: ^2.0.3
  font_awesome_flutter: ^9.0.0
  spreadsheet_decoder: ^2.0.0

  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_windows: ^0.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  build_runner: ^2.0.4
  mocktail: ^0.1.4
  test: ^1.16.8
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.1

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/counters_import_template.png
    - assets/sql/
