name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
      
      - name: Build requests module
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: copyLibsToParentProject
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          build-root-directory: requests_processor2
      
      - name: Copy requests module
        shell: powershell
        run: xcopy /S "requests" "build\windows\runner\Release\requests\"

      - name: Copy required libs
        shell: powershell
        run: xcopy /S "requirements\*.dll" "build\windows\runner\Release\"

      # Upload generated Windows build to the artifacts.
      - uses: actions/upload-artifact@v2
        with:
          name: Windows build
          path: build/windows/runner/Release/
