name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows

      - name: Copy requests module
        shell: powershell
        run: xcopy /S "requests\" "build\windows\runner\Release\requests\"

      - name: Copy requires libs
        shell: powershell
        run: xcopy /S "requirements\*.dll" "build\windows\runner\Release\"

      # Upload generated Windows build to the artifacts.
      - uses: actions/upload-artifact@v2
        with:
          name: Windows build
          path: build/windows/runner/Release/
